Detailpage
ComicScrip/lyon-react-mars22-p2g2 pull request #31
Opened 2022-04-20 08:24 UTC by QuintinJouanne

2022-04-24 10:46 UTC, ComicScrip requested changes

2022-04-24 10:46 UTC, ComicScrip commented on src/routes/DetailPage.js
> +  const [arrayApi, setArrayApi] = useState([]);
on aurait pu choisir un nom plus explicite

2022-04-24 10:46 UTC, ComicScrip commented on src/components/Main.js
> +        <Route path="/detailpage" element={<DetailPage />} />
la route devrait prendre en compte un identifiant

2022-04-24 10:46 UTC, ComicScrip commented on src/routes/DetailPage.js
> +        'https://imdb-api.com/en/API/SearchMovie/k_9vhe3kdy/inception%202010'
il y a surement une autre route pour récupérer les détails d'un film sous la forme d'un objet, non ?

2022-04-29 07:33 UTC, JVRasa commented
Pull request sur la mauvaise branche détail

2022-04-29 07:33 UTC, closed without merging